sudo: false
language: r
cache: packages

before_install:
    - tlmgr install filecontents
    - tlmgr install natbib

# whitelist
branches:
  only:
    - master

after_success:
  - Rscript -e 'covr::codecov(type = "all", commentDontrun = FALSE, commentDonttest = FALSE)'
