sudo: false
language: r
r:
  - oldrel
  - release
  - devel

env:
  global:
    - R_CHECK_ARGS="--as-cran"

before_install:
    - tlmgr install filecontents
    - tlmgr install natbib

r_github_packages:
    - jimhester/covr

addons:
  apt:
    packages:
      - mesa-common-dev
      - libglu1-mesa-dev

script:
    - |
      R CMD build .
      travis_wait 30 R CMD check --as-cran cpr_*.tar.gz

# whitelist
branches:
  only:
    - master

after_failure:
    find *Rcheck -name '*.fail' -print -exec cat '{}' \;

after_success:
  - Rscript -e 'covr::codecov(type = "all", commentDontrun = FALSE, commentDonttest = FALSE)'

