## @knitr cpr_jss_setup
set.seed(42)  # don't panic, this is reproducible.
knitr::opts_chunk$set(echo       = TRUE,
                      cache      = TRUE,
                      cache.dir  = "cpr-pkg_cache",
                      results    = 'markup',
                      eval.after = 'fig.cap',
                      fig.width  = 5,
                      fig.height = 5)
knitr::render_sweave() # use boring Sweave environments
knitr::set_header(highlight = '') # do not use the Sweave.sty package
pdf.options(family = 'Palatino')
options(width = 84, digits = 3, prompt = 'R> ', continue = "+  ",
        str = strOptions(strict.width = "wrap",
                         digits.d = 3,
                         vec.len = 4,
                         formatNum = function(x, ...)
                           format(x, trim = TRUE, drop0trailing = TRUE, ...)))

library(qwraps2)
library(splines)
library(lme4)
library(cpr)
library(plot3D)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(rbenchmark)

## @knitr bsplines_vs_bs_calls
xvec <- seq(0, 6, length = 500) # a vector to construct a B-spline basis for
iknots <- sort(runif(6))        # 6 randomly located internal knots

# show that splines::bs and cpr::bsplines generate the same basis
all.equal(unclass(bs(xvec, knots = iknots)), 
          unclass(bsplines(xvec, iknots = iknots)[, -1]),
          check.attributes = FALSE)
all.equal(unclass(bs(xvec, knots = iknots, intercept = TRUE)), 
          unclass(bsplines(xvec, iknots = iknots)),
          check.attributes = FALSE)

## @knitr eg_bmat
bmat <- bsplines(x      = seq(0, 6, length = 500),
                 iknots = c(1.0, 1.5, 2.3, 4.0, 4.5))

## @knitr eg_bmat_str
bmat
str(bmat)

## @knitr eg_basis_plot
plot(bmat, show_xi = TRUE, show_x = TRUE,  color = FALSE, digits = 1) +
theme(text = element_text(family = "Times", size = 10))

## @knitr eg_cp.cpr_bs
theta <- c(1, 0, 3.5, 4.2, 3.7, -0.5, -0.7, 2, 1.5)
eg_cp <- cp(bmat, theta)

## @knitr eg_cp.cpr_bs_str
str(eg_cp)

## @knitr eg_spline_and_cp
# plot_a is the basis
basis_plot <- plot(bmat, show_x = TRUE, digits = 1)

# cp_plot is the spline and control polygon.  Use the same set up as the basis
# plot, but remove the layers and replace with layers for the spline function
# and the control polygon.
# the graphics generated by plot(cp(bmat, theta)) are insufficient for the
# background section of the paper but sufficient when working with the package.
cp_plot0 <- basis_plot
cp_plot0[[which(names(cp_plot0) == "layers")]] <- NULL

cp_plot0 +
geom_line(mapping = aes(x = xi_star, y = theta), data = eg_cp$cp,
          inherit.aes = FALSE, linetype = 3) +
geom_line(mapping = aes(x = x, y = y), data = get_spline(eg_cp)$spline,
          inherit.aes = FALSE) +
geom_point(mapping = aes(x = xi_star, y = theta),
           data = eg_cp$cp, inherit.aes = FALSE) +
theme(text = element_text(family = "Times", size = 10))

## @knitr eg_influence_weights
# Data
omit_xi <- influence_of(cp(bmat, theta), c(6, 8))

# influence_data: need to construct this data.frame for plotting.  The version
# of the influce plots used in section 5 of the manuscript is far simpler.
influence_data <-
  bind_rows(rename(eg_cp$cp, x = xi_star, y = theta),
            get_spline(eg_cp)$spline,
            rename(omit_xi$coarsened_cp[[1]]$cp, x = xi_star, y = theta) , 
            get_spline(omit_xi$coarsened_cp[[1]])$spline,
            rename(omit_xi$coarsened_cp[[2]]$cp, x = xi_star, y = theta),
            get_spline(omit_xi$coarsened_cp[[2]])$spline,
            rename(omit_xi$reinserted_cp[[1]]$cp, x = xi_star, y = theta),
            get_spline(omit_xi$reinserted_cp[[1]])$spline,
            rename(omit_xi$reinserted_cp[[2]]$cp, x = xi_star, y = theta),
            get_spline(omit_xi$reinserted_cp[[2]])$spline,
            .id = "object")

influence_data$CP <- NA
influence_data$CP <- gsub("^[1-2]$", "Original", influence_data$object)
influence_data$CP <- gsub("^[3-6]$", "Omit a knot", influence_data$CP)
influence_data$CP <- gsub("^([7-9]|10)$", "Reinsert the knot", influence_data$CP)
influence_data$CP <-
  factor(influence_data$CP,
         levels = c("Original", "Omit a knot", "Reinsert the knot"))

influence_data <-
  bind_rows(filter(influence_data, object %in% c(1:2, 3:4)),
            filter(influence_data, object %in% c(1:2, 3:4, 7:8)),
            filter(influence_data, object %in% c(1:2, 5:6)),
            filter(influence_data, object %in% c(1:2, 5:6, 9:10)),
            .id = "facets")
 
influence_data$facets <-
  factor(influence_data$facets,
         levels = 1:4,
         labels = c("Omitting ~ xi[6]", "Reinserting ~ xi[6]",
                    "Omitting ~ xi[8]", "Reinserting ~ xi[8]")) 

influence_weight_plot <- plot(bmat, show_x = FALSE)
influence_weight_plot[[which(names(influence_weight_plot) == "layers")]] <- NULL

influence_weight_plot <-
  influence_weight_plot %+%
    influence_data +
    facet_wrap( ~ facets, labeller = label_parsed) +
    aes(x = x, y = y, color = NULL, alpha = CP, shape = CP, linetype = CP,
        group = object) +
    geom_point(data = filter(influence_data, object %in% seq(1, 9, by = 2))) +
    geom_line() +
    theme(axis.ticks.y     = element_blank(),
          axis.text.y      = element_blank(),
          panel.grid       = element_blank(),
          legend.position  = "bottom",
          legend.key.width = unit(0.5, "inch"),
          legend.title     = element_blank()) +
    scale_alpha_discrete(range = c(0.5, 1)) +
    coord_cartesian(ylim = c(-1.3, 4.8)) +
    theme(text = element_text(family = "Times", size = 10))

influence_weight_plot

## @knitr eg_cn.cpr_bt
tpmat <- btensor(x = list(seq(0, 1, length = 51),
                          seq(0, 1, length = 51)),
                 iknots = list(numeric(0), 
                               c(0.418, 0.582, 0.676, 0.840)),
                 order = list(3, 4))
theta <- 
  c(-0.03760,  0.03760, -0.03760,  0.77579, -0.84546,  0.63644, -0.87674,
     0.71007, -1.21007,  0.29655, -0.57582, -0.26198,  0.23632, -0.58583,
    -0.46271, -0.39724, -0.02194, -1.23562, -0.19377, -0.27948, -1.14028,
     0.00405, -0.50405, -0.99595)

eg_cn <- cn(tpmat, theta)

## @knitr eg_plot_cn.cpr_bt_a
plot(eg_cn, rgl = FALSE, xlab = "x1", ylab = "x2", clim = c(-1.2, 0.28))

## @knitr eg_plot_cn.cpr_bt_b
plot(eg_cn, show_net = FALSE, show_surface = TRUE, rgl = FALSE, xlab = "x1", ylab = "x2", clim = c(-1.2, 0.28))

## @knitr spdg_summary
glimpse(spdg)
summary(spdg)

## @knitr spdg_plot1
ggplot(spdg) +
theme_bw(base_family = "Times") +
aes_string(x = "day_of_cycle", y = "pdg", group = "id") +
geom_path(alpha = 0.05) +
geom_point(data = function(x) {filter(x, day_from_dlt == 0)},
           shape = 3, color = 'grey50') +
scale_y_log10() +
annotation_logticks(sides = "l")

## @knitr spdg_plot2
ggplot(spdg) +
theme_bw(base_family = "Times") +
aes_string(x = "day", y = "pdg", group = "id") +
geom_path(alpha = 0.05) +
geom_point(data = function(x) {filter(x, day_from_dlt == 0)},
           shape = 3, color = 'grey50') +
scale_y_log10() +
annotation_logticks(sides = "l")

## @knitr trimmed_quantile_eg1
# A data vector
x <- c(rep(0, 4), runif(100, 0, 1), rep(1, 20))

# equivalent call to quantile requires edits to be made to x
x2 <- unique(x)
x2 <- x2[!(x2 %in% range(x2))]

all.equal(quantile(x2), trimmed_quantile(x))

## @knitr trimmed_qantile_eg2
# Increase the trim to five
x2 <- unique(x)
for(i in 1:5) { x2 <- x2[!(x2 %in% range(x2))] }

all.equal(quantile(x2), trimmed_quantile(x, trim = 5L))


## @knitr matrices_A_and_B
A <- matrix(c(-1, -1, -1, 1, 1, 1), nrow = 3)
A
B <- matrix(1:15, nrow = 3)
B

## @knitr tensor_AB
build_tensor(A, B)

## @knitr tensor_BA
build_tensor(B, A)

## @knitr methods_update_b
# Methods for update_bsplines and update_btensor
methods(update_bsplines)
methods(update_btensor)

## @knitr benchmark_matrix_rank
mat <- matrix(rnorm(25000 * 120), nrow = 25000)
Matrix::rankMatrix(mat)[1]
matrix_rank(mat)
benchmark(Matrix::rankMatrix(mat)[1], matrix_rank(mat),
          columns = c("test", "replications", "elapsed", "relative"))

## @knitr cp.formula_args
str(cpr:::cp.formula)

## @knitr calling_cp.formula
dat <- tibble::data_frame(x = seq(-pi, pi, length = 200),
                          y = sin(x))
eg_cp2 <- cp(y ~ bsplines(x = x, df = 14), data = dat)










## @knitr eg_model_matrix_part_1
# Default model.matrix
m <- model.matrix( ~ bsplines(day) + age + ttm + ethnicity, data = spdg)
head(m, 2)
c(columns = ncol(m), rank = matrix_rank(m))

## @knitr eg_model_matrix_part_2
# Default model.matrix with a zero intercept
m <- model.matrix( ~ bsplines(day) + age + ttm + ethnicity + 0, data = spdg)
head(m, 2)
c(columns = ncol(m), rank = matrix_rank(m))

## @knitr eg_model_matrix_part_3
# Default model.matrix from a cp call
cp_lm_fit <- update(update_bsplines(cp_lm, df = NULL), keep_fit = TRUE)$fit
formula(cp_lm_fit)
m <- as.matrix(cp_lm_fit$model)
head(m, 2)
m <- m[, -1]  # m[, -1] omits the response column
c(columns = ncol(m), rank = matrix_rank(m))

## @knitr cp_lm_str
str(cp_lm)

## @knitr plot.cpr_cp
plot(cp_lm, cp_lmer) + theme(legend.position = "bottom") # Figure \ref{fig:cp_lm_cp_lmer_plots}

## @knitr cp_knot_influence_weights
influence_weights(eg_cp)

## @knitr influence_of
influence_of(eg_cp)
str(influence_of(eg_cp), max.level = 1)

## @knitr influence_of_plots
# find the influence of xi_6 on the eg control polygon
influ_xi6 <- influence_of(eg_cp, 6)

# create the graphic seen in Figure \ref{fig:cp_knot_influence_plot}
plot(influ_xi6$orig_cp,
     influ_xi6$coarsened_cp[[1]],
     influ_xi6$reinserted_cp[[1]], 
     show_spline = TRUE, 
     color = TRUE) +
  theme(legend.position = "bottom")

## @knitr initial_cp_4
initial_cp_4 <-
  cp(log10(pdg) ~ bsplines(day, df = 54) + age + ttm + ethnicity + (1 | id), 
     data = spdg, 
     method = lmer)

## @knitr initial_cp_4_plot
plot(initial_cp_4)

## @knitr cpr_run_4
system.time(cpr_run_4 <- cpr(initial_cp_4))
cpr_run_4
summary(cpr_run_4)

## @knitr cpr_run_4_plots
# Figure \ref{fig:cpr_run_4_plots\string-1}
plot(cpr_run_4, from = 3, to = 7, color = TRUE) + 
  theme(legend.position = "bottom") +
  guides(color    = guide_legend(nrow = 2),
         linetype = guide_legend(nrow = 2))

# Figure \ref{fig:cpr_run_4_plots\string-2}
plot(cpr_run_4, type = "rmse", to = 10)

## @knitr cpr_run_3_and_2
initial_cp_3 <- update_bsplines(initial_cp_4, df = 53, order = 3)
system.time(cpr_run_3 <- cpr(initial_cp_3))

initial_cp_2 <- update_bsplines(initial_cp_4, df = 52, order = 2)
system.time(cpr_run_2 <- cpr(initial_cp_2))

## @knitr cpr_run_3_plots
plot(cpr_run_3)                         # Figure \ref{fig:cpr_run_3_plots\string-1}
plot(cpr_run_3, from = 3, to = 5)       # Figure \ref{fig:cpr_run_3_plots\string-2}
plot(cpr_run_3, type = "rmse", to = 10) # Figure \ref{fig:cpr_run_3_plots\string-3}

## @knitr cpr_run_2_plots
plot(cpr_run_2)
plot(cpr_run_2, from = 3, to = 5)
plot(cpr_run_2, type = "rmse")
plot(cpr_run_2, type = "rmse", to = 10)
plot(cpr_run_2, type = "loglik", to = 10)

## @knit cpr_run_4v3v2
summary(cpr_run_4)[4, ]
summary(cpr_run_3)[3, ]
summary(cpr_run_2)[5, ]

plot(cpr_run_4[[4]], cpr_run_3[[3]], show_spline = TRUE, show_cp = FALSE)

## @knitr cpr_predict
newdata <-
  expand.grid(day = seq(-1, 1, length = 500), 
              age = median(spdg$age),
              ttm = median(spdg$ttm),
              ethnicity = factor("Caucasian", levels = levels(spdg$ethnicity)),
              id = NA, pdg = NA)

str(predict(cpr_run_4[[4]], newdata = newdata))

## @knitr cpr_predict_plotdata
plotdata <-
  bind_rows(cbind(newdata, predict(cpr_run_4[[4]], newdata = newdata)),
            cbind(newdata, predict(cpr_run_3[[3]], newdata = newdata)), 
            .id = "cpr_run") 
plotdata$cpr_run <- factor(plotdata$cpr_run, 1:2, c("cpr_run_4[[4]]", "cpr_run_3[[3]]"))

## @knitr cpr_cp_recover_regression_object
class(cpr_run_3[[3]]$fit) # No regression model
# recover the regression object
cpr_run_3[[3]] <- update(cpr_run_3[[3]], keep_fit = TRUE)
class(cpr_run_3[[3]]$fit) # a lmerMod object

## @knitr cpr_predict_plot_1
ggplot(plotdata) +
theme_bw() +
aes(x = day, y = pred, ymin = pred - se, ymax = pred + se, color = cpr_run, linetype = cpr_run)+
geom_path() +
ylab("log10(pdg)") +
theme(legend.position = "bottom",
      legend.title = element_blank()) 

## @knitr cpr_predict_plot_2
ggplot(plotdata) +
theme_bw() +
aes(x = day, y = pred, ymin = pred - se, ymax = pred + se, color = cpr_run, linetype = cpr_run)+
geom_ribbon(fill = NA) +
ylab("log10(pdg)") +
theme(legend.position = "bottom",
      legend.title = element_blank()) 

## @knitr cpr_bt_args
str(bsplines)
str(btensor)

## @knitr cpr_br_example
x1 <- x2 <- seq(0, 1, length = 51)  # two continuous variables
bt <- btensor(x = list(x1, x2), df = list(5, 10), order = list(3L, 4L))
bt
str(bt, max.level = 1L)

## @knitr two_level_cat_bspline
bsplines(rep(0:1, 3), order = 2L)

## @knitr four_level_cat_bspline
bsplines(rep(0:3, 3), iknots = 1:2, order = 2L)

## @knitr two_con_one_cat_btensor
x3 <- rep(0:2, 17)  # a three level categorial variable

bt2_iknots <-
  c(lapply(attr(bt, "bspline_list"), attr, which = "iknots"), # iknots from bt
    1) # iknot for x3

bt2 <- btensor(x = list(x1, x2, x3), iknots = bt2_iknots, order = list(3L, 4L, 2L))
bt2
str(bt2, max.level = 1L)

## @knitr verify_two_con_one_cat_btensor
mapply(all.equal,
       target = attr(bt2, "bspline_list"),
       current = list(bsplines(x1, df = 5, order = 3),
                      bsplines(x2, df = 10),
                      bsplines(x3, iknots = 1, order = 2)),
       MoreArgs = list(check.attributes = FALSE))

## @knitr influence_weights.cpr_cn
f <- function(x1, x2) {(x1 - 0.5)^2 * sin(4 * pi * x2) - x1 * x2} 
eg_data <- 
  data_frame(x1 = rep(seq(0, 1, length = 51), times = 51),
             x2 = rep(seq(0, 1, length = 51), each  = 51),
             z  = f(x1, x2))

# control net for the function f, B-spline orders 3 and 4
cn_f_34 <-
  cn(z ~ btensor(list(x1, x2), 
                 iknots = list(c(0.234), c(0.418, 0.582, 0.676, 0.840)),
                 order = c(3L, 4L)),
     data = eg_data)

influence_weights(cn_f_34)

## @knitr influence_weights.cpr_cn2
influence_weights(cn_f_34, margin = 2)

## @knitr cn_influence_plots_a
persp3D(x = unique(eg_data$x1), y = unique(eg_data$x2),
        z = matrix(eg_data$z, nrow = 51, ncol = 51),
        xlab = "x1", ylab = "x2", clim = c(-1.2, 0.28))

## @knitr cn_influence_plots_b
cn_f_34_omit1 <-
  update_btensor(cn_f_34, iknots = list(numeric(0), c(0.418, 0.582, 0.676, 0.840)))
eg_data <- bind_cols(eg_data, predict(cn_f_34_omit1, newdata = eg_data))
eg_data <- rename(eg_data, pred_omit_1 = pred, se_omit_1 = se)
persp3D(x = unique(eg_data$x1), y = unique(eg_data$x2),
        z = matrix(eg_data$pred_omit_1, nrow = 51, ncol = 51),
        xlab = "x1", ylab = "x2", clim = c(-1.2, 0.28))

## @knitr cn_influence_plots_c
cn_f_34_omit2 <-
  update_btensor(cn_f_34, iknots = list(0.234, c(0.582, 0.676, 0.840)))
eg_data <- bind_cols(eg_data, predict(cn_f_34_omit2, newdata = eg_data))
eg_data <- rename(eg_data, pred_omit_2 = pred, se_omit_2 = se)
persp3D(x = unique(eg_data$x1), y = unique(eg_data$x2),
        z = matrix(eg_data$pred_omit_2, nrow = 51, ncol = 51),
        xlab = "x1", ylab = "x2", clim = c(-1.2, 0.28))

## @knitr cnr_f_44
initial_cn_f_44 <-
  cn(z ~ btensor(list(x1, x2), df = c(44, 44), order = c(4L, 4L)),
     data = eg_data)
cnr_f_44 <- cnr(initial_cn_f_44)

## @knitr cnr_f_44_plot
plot(cnr_f_44, to = 20)

## @knitr cnr_f_44_summary
summary(cnr_f_44)

## @knitr cnr_f_34
initial_cn_f_34 <-
  update_btensor(initial_cn_f_44, df = c(43, 44), order = c(3L, 4L)) 
cnr_f_34 <- cnr(initial_cn_f_34)

## @knitr cnr_f_34_plot
plot(cnr_f_34, to = 20)

## @knitr cnr_f_34_summary
summary(cnr_f_34)

## @knitr cnr_f_24
initial_cn_f_24 <-
  update_btensor(initial_cn_f_44, df = c(42, 44), order = c(2L, 4L)) 
cnr_f_24 <- cnr(initial_cn_f_24)

## @knitr cnr_f_comperative_plot_a
bind_rows(mutate(summary(cnr_f_44), index = seq_along(dfs)),
          mutate(summary(cnr_f_34), index = seq_along(dfs)),
          mutate(summary(cnr_f_24), index = seq_along(dfs)),
          .id = "cnr_f_") %>%
mutate(cnr_f_ = factor(cnr_f_, 1:3, c("44", "34", "24"))) %>%
filter(index < 21) %>%
ggplot(.) +
theme_bw() +
aes(x = index, y = rmse, color = cnr_f_, linetype = cnr_f_) + 
geom_line() +
theme(legend.position = "bottom")

## @knitr cnr_f_comperative_plot_b
bind_rows(mutate(summary(cnr_f_44), index = seq_along(dfs)),
          mutate(summary(cnr_f_34), index = seq_along(dfs)),
          mutate(summary(cnr_f_24), index = seq_along(dfs)),
          .id = "cnr_f_") %>%
mutate(cnr_f_ = factor(cnr_f_, 1:3, c("44", "34", "24"))) %>%
filter(index < 21) %>%
ggplot(.) +
theme_bw() +
aes(x = dfs, y = rmse, color = cnr_f_, linetype = cnr_f_) + 
geom_line() +
theme(legend.position = "bottom")

## @knitr cnr_f_comperative_summary
summary(cnr_f_44)[7, ]
summary(cnr_f_34)[7, ]

## @knitr cnr_f_comperative_se_1
newdat <- expand.grid(x1 = seq(0, 1, length = 101),
                      x2 = seq(0, 1, length = 101),
                      z  = NA)
pred_f_44 <- predict(cnr_f_44[[7]], newdata = newdat)
pred_f_34 <- predict(cnr_f_34[[7]], newdata = newdat)

newdat <- cbind(newdat,
                rename(pred_f_44, pred_44 = pred, se_44 = se),
                rename(pred_f_34, pred_34 = pred, se_34 = se)) 

persp3D(unique(newdat$x1), unique(newdat$x2),
        matrix(newdat$pred_44, nrow = n_distinct(newdat$x1)),
        xlab = "x1", ylab = "x2",
        zlim = c(-1.1, 0.38),
        clim = c(-1.1, 0.38))
persp3D(unique(newdat$x1), unique(newdat$x2),
        matrix(newdat$pred_44 + 1000 * newdat$se_44, nrow = n_distinct(newdat$x1)),
        xlab = "x1", ylab = "x2", alpha = 0.3,
        zlim = c(-1.1, 0.38),
        clim = c(-1.1, 0.38), colkey = FALSE,
        add = TRUE)
persp3D(unique(newdat$x1), unique(newdat$x2),
        matrix(newdat$pred_44 - 1000 * newdat$se_44, nrow = n_distinct(newdat$x1)),
        xlab = "x1", ylab = "x2", alpha = 0.3,
        zlim = c(-1.1, 0.38),
        clim = c(-1.1, 0.38), colkey = FALSE,
        add = TRUE)

## @knitr cnr_f_comperative_se_2
persp3D(unique(newdat$x1), unique(newdat$x2),
        matrix(newdat$pred_34, nrow = n_distinct(newdat$x1)),
        xlab = "x1", ylab = "x2",
        zlim = c(-1.1, 0.38),
        clim = c(-1.1, 0.38))
persp3D(unique(newdat$x1), unique(newdat$x2),
        matrix(newdat$pred_34 + 1000 * newdat$se_34, nrow = n_distinct(newdat$x1)),
        xlab = "x1", ylab = "x2", alpha = 0.3,
        zlim = c(-1.1, 0.38),
        clim = c(-1.1, 0.38), colkey = FALSE,
        add = TRUE)
persp3D(unique(newdat$x1), unique(newdat$x2),
        matrix(newdat$pred_34 - 1000 * newdat$se_34, nrow = n_distinct(newdat$x1)),
        xlab = "x1", ylab = "x2", alpha = 0.3,
        zlim = c(-1.1, 0.38),
        clim = c(-1.1, 0.38), colkey = FALSE,
        add = TRUE)


## @knitr spdg_init_cn_344
iknots_list <-
  list(cpr_run_3[[3]]$iknots,
       unname(trimmed_quantile(spdg$age, prob = 1:12/13)[-c(1, 12)]),
       unname(trimmed_quantile(spdg$ttm, prob = 1:12/13)[-c(1, 12)]))

spdg_init_cn_344 <-
  cn(log10(pdg) ~ btensor(x = list(day, age, ttm),
                          iknots = iknots_list,
                          order = list(3, 4, 4)) +
                  ethnicity + (1 | id),
     data = spdg,
     method = lmer)

## @knitr cnr_run_344
cnr_run_344 <- cnr(spdg_init_cn_344, margin = 2:3)

## @knitr cnr_run_344_rmse
plot(cnr_run_344)

## @knitr cnr_run_344_comp
s11 <- get_surface(cnr_run_344[[1]], margin = 2:3, at = list(-0.5, NA, NA))
s12 <- get_surface(cnr_run_344[[1]], margin = 2:3, at = list( 0.5, NA, NA))
s71 <- get_surface(cnr_run_344[[7]], margin = 2:3, at = list(-0.5, NA, NA))
s72 <- get_surface(cnr_run_344[[7]], margin = 2:3, at = list( 0.5, NA, NA))

par(mfrow = c(2, 2))
persp3D(x = unique(s11$surface$Var2), y = unique(s11$surface$Var3),
        z = matrix(s11$surface$z, nrow = 100, ncol = 100),
        xlab = "age", ylab = "ttm",
        main = "Age and TTM interaction at day = -0.5\n80 df",
        NAcol = "grey70",
        clim = c(-0.9, -0.1),
        zlim = c(-0.9, -0.1))
persp3D(x = unique(s71$surface$Var2), y = unique(s71$surface$Var3),
        z = matrix(s71$surface$z, nrow = 100, ncol = 100),
        xlab = "age", ylab = "ttm", 
        main = "Age and TTM interaction at day = -0.5\n255 df",
        NAcol = "grey70",
        clim = c(-0.9, -0.1),
        zlim = c(-0.9, -0.1))

persp3D(x = unique(s12$surface$Var2), y = unique(s12$surface$Var3),
        z = matrix(s12$surface$z, nrow = 100, ncol = 100),
        xlab = "age", ylab = "ttm",
        main = "Age and TTM interaction at day = 0.5\n80 df",
        NAcol = "grey70",
        clim = c(0.1, 1.1),
        zlim = c(0.1, 1.1))
persp3D(x = unique(s72$surface$Var2), y = unique(s72$surface$Var3),
        z = matrix(s72$surface$z, nrow = 100, ncol = 100),
        xlab = "age", ylab = "ttm",
        main = "Age and TTM interaction at day = 0.5\n255 df",
        NAcol = "grey70",
        clim = c(0.1, 1.1),
        zlim = c(0.1, 1.1))

## @knitr spdg_init_cn_334
spdg_init_cn_334 <- update_btensor(spdg_init_cn_344, order = list(3, 3, 4))

## @knitr spdg_init_cn_324
spdg_init_cn_324 <- update_btensor(spdg_init_cn_344, order = list(3, 2, 4))

## @knitr spdg_init_cn_343
spdg_init_cn_343 <- update_btensor(spdg_init_cn_344, order = list(3, 4, 3))

## @knitr spdg_init_cn_342
spdg_init_cn_342 <- update_btensor(spdg_init_cn_344, order = list(3, 4, 2))

## @knitr spdg_init_cn_333
spdg_init_cn_333 <- update_btensor(spdg_init_cn_344, order = list(3, 3, 3))

## @knitr spdg_init_cn_323
spdg_init_cn_323 <- update_btensor(spdg_init_cn_344, order = list(3, 2, 3))

## @knitr spdg_init_cn_332
spdg_init_cn_332 <- update_btensor(spdg_init_cn_344, order = list(3, 3, 2))

## @knitr spdg_init_cn_322
spdg_init_cn_322 <- update_btensor(spdg_init_cn_344, order = list(3, 2, 2))

## @knitr cnr_run_334
cnr_run_334 <- cnr(spdg_init_cn_334, margin = 2:3)

## @knitr cnr_run_324
cnr_run_324 <- cnr(spdg_init_cn_324, margin = 2:3)

## @knitr cnr_run_343
cnr_run_343 <- cnr(spdg_init_cn_343, margin = 2:3)

## @knitr cnr_run_342
cnr_run_342 <- cnr(spdg_init_cn_342, margin = 2:3)

## @knitr cnr_run_333
cnr_run_333 <- cnr(spdg_init_cn_333, margin = 2:3)

## @knitr cnr_run_332
cnr_run_332 <- cnr(spdg_init_cn_332, margin = 2:3)

## @knitr cnr_run_323
cnr_run_323 <- cnr(spdg_init_cn_323, margin = 2:3)

## @knitr cnr_run_322
cnr_run_322 <- cnr(spdg_init_cn_322, margin = 2:3)

## @knitr cnr_run_rmse_comp
bind_rows(mutate(summary(cnr_run_344), index = seq_along(dfs)),
          mutate(summary(cnr_run_322), index = seq_along(dfs)),
          .id = "cnr_run_") %>%
mutate(cnr_run_ = factor(cnr_run_, 1:2, c("344", "322"))) %>%
ggplot(.) +
theme_bw() +
aes(x = index, y = rmse, color = cnr_run_, linetype = cnr_run_, shape = cnr_run_) +
geom_line(alpha = 0.5) +
geom_point() +
geom_text(mapping = aes(label = dfs), nudge_y = 0.00009) +
theme(legend.position = "bottom")

## @knitr cnr_run_322_surfaces_a
s322_1 <- get_surface(cnr_run_322[[1]], margin = 2:3, at = list(-1.00, NA, NA)) 
persp3D(x = unique(s322_1$surface$Var2),
        y = unique(s322_1$surface$Var3),
        z = matrix(s322_1$surface$z, nrow = 100, ncol = 100),
        xlab = "age", ylab = "ttm",
        main = "Age and TTM interaction\nFirst Day of Menses",
        zlim = mean(s322_1$surface$z) + c(-0.15, 0.15))

## @knitr cnr_run_322_surfaces_b
s322_2 <- get_surface(cnr_run_322[[1]], margin = 2:3, at = list(-0.50, NA, NA))
persp3D(x = unique(s322_2$surface$Var2),
        y = unique(s322_2$surface$Var3),
        z = matrix(s322_2$surface$z, nrow = 100, ncol = 100),
        xlab = "age", ylab = "ttm",
        main = "Age and TTM interaction\nMidway through the Follicular Phase",
        zlim = mean(s322_2$surface$z) + c(-0.15, 0.15))

## @knitr cnr_run_322_surfaces_c
s322_3 <- get_surface(cnr_run_322[[1]], margin = 2:3, at = list( 0.00, NA, NA))
persp3D(x = unique(s322_3$surface$Var2),
        y = unique(s322_3$surface$Var3),
        z = matrix(s322_3$surface$z, nrow = 100, ncol = 100),
        xlab = "age", ylab = "ttm",
        main = "Age and TTM interaction\nDay of Luteal Transition",
        zlim = mean(s322_3$surface$z) + c(-0.15, 0.15))

## @knitr cnr_run_322_surfaces_d
s322_4 <- get_surface(cnr_run_322[[1]], margin = 2:3, at = list( 0.50, NA, NA))
persp3D(x = unique(s322_4$surface$Var2),
        y = unique(s322_4$surface$Var3),
        z = matrix(s322_4$surface$z, nrow = 100, ncol = 100),
        xlab = "age", ylab = "ttm",
        main = "Age and TTM interaction\nMidway through Luteal Phase",
        zlim = mean(s322_4$surface$z) + c(-0.15, 0.15))

## @knitr cnr_run_322_surfaces_e
s322_5 <- get_surface(cnr_run_322[[1]], margin = 2:3, at = list( 1.00, NA, NA))
persp3D(x = unique(s322_5$surface$Var2),
        y = unique(s322_5$surface$Var3),
        z = matrix(s322_5$surface$z, nrow = 100, ncol = 100),
        xlab = "age", ylab = "ttm",
        main = "Age and TTM interaction\nEnd of Cycle",
        zlim = mean(s322_5$surface$z) + c(-0.15, 0.15)) 

## @knitr cleanup
