# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_bsplines <- function(x, iknots, bknots, order) {
    .Call('_cpr_cpp_bsplines', PACKAGE = 'cpr', x, iknots, bknots, order)
}

cpp_bsplinesD1 <- function(x, iknots, bknots, order) {
    .Call('_cpr_cpp_bsplinesD1', PACKAGE = 'cpr', x, iknots, bknots, order)
}

cpp_bsplinesD2 <- function(x, iknots, bknots, order) {
    .Call('_cpr_cpp_bsplinesD2', PACKAGE = 'cpr', x, iknots, bknots, order)
}

W <- function(x, xi, k) {
    .Call('_cpr_W', PACKAGE = 'cpr', x, xi, k)
}

